### ISSUE TITLE
Redskyblock

### ISSUE THREAD

**Issue by jennocool** [TheRealKizu/SkyBlockUI#5] opened 2019-12-08 18:29 UTC
Can you adjust it for redskyblock because I think redskyblock is better

**Comment by TheRealKizu** [comment] 2019-12-10 03:47
I will in the future :). I'm busy right now on my school projects and my server

**Comment by TheRealKizu** [comment] 2019-12-10 03:47
Duplicate of #3

**Comment by jennocool** [comment] 2019-12-10 19:15
nice ;)

**Comment by TheRealKizu** [comment] 2019-12-11 09:30
Progress can be found on the redsb branch ;)

**Comment by TheRealKizu** [comment] 2020-01-01 22:21
Also chat now on #3

**Closed by TheRealKizu** 2020-01-01 22:21 UTC
Labels: enhancement, todo
